piVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: publish
    service: app
    track: stable
  name: publish-app
  namespace: buffer
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: publish
      service: app
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: publish
        service: app
        track: stable
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        name: publish-app
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dhbufferapp
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  observedGeneration: 16
  replicas: 2
  updatedReplicas: 2